# Generated by Django 5.2.8 on 2025-12-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_conversionhistory_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
